hydra:
  run:
    dir: ./
  output_subdir: ./

nwp_model: ch2  # Can only be ch2 for this project
d_map:
  ch2: 96

model: 
  type: "MultiScaleGraphWaveNet"
  kwargs: 
    emb_dim : 16
    channels: 32
    layers: 3
    drop: 0.2
    output_dist: LogNormal
    dil: [1, 2, 4, 8]
    kernels: [1, 3, 5, 7]
    history_dropout_p: 0.07
    history_block: 12
    dynamic: [True]
    node_emb_dim: 20
    

graph_kwargs:
  knn: 5
  threshold: 0.6
  theta: "std"
    
seed: 0

training: 
  batch_size: 32
  loss: "MaskedCRPSLogNormal"
  gradient_clip_value: 1.0
  epochs: 100
  optim:
    algo: 'Adam'
    kwargs:
      betas: "(0.9, 0.999)"
      lr: 0.0001
      weight_decay: 0
  scheduler:
    algo: 'OneCycleLR'
    kwargs: 
      T_0: 20
      T_mult: 2
      eta_min: 0.000005
      step_size: 1
      t_max: 100
      step_gamma: 0.5
      gamma: 0.5
      exp_gamma: 0.9
      max_lr: 0.001
      epochs: 100
      steps_per_epoch: 175
      div_factor: 25
      pct_start: 0.5

logging:
  mlflow_tracking_uri: ${oc.env:MLFLOW_TRACKING_URI, mlruns} # log locally 
  experiment_id: MultiScaleWave_wind_postproc

data_base_folder: ${oc.env:DATA_BASE_FOLDER}
dataset:
  hours_leadtime: "${d_map.${nwp_model}}" # Depends on nwp model 
  train_split: 0.8
  val_split: 0.2
  test_start: '2024-05-16'
  train_val_end: '2023-09-30'
  features_pth: ${data_base_folder}/features.nc
  targets_pth: ${data_base_folder}/targets.nc
  predictors:
  - ${nwp_model}:wind_speed_ensavg
  - ${nwp_model}:wind_speed_ensstd
  - ${nwp_model}:mslp_difference_GVE_GUT_ensavg
  - ${nwp_model}:mslp_difference_BAS_LUG_ensavg
  - time:sin_hourofday
  - time:cos_hourofday
  - time:sin_dayofyear
  - time:cos_dayofyear
  - terrain:elevation_50m
  - terrain:distance_to_alpine_ridge
  - terrain:tpi_2000m
  - terrain:std_2000m
  - terrain:valley_norm_2000m
  - terrain:sn_derivative_500m
  - terrain:sn_derivative_2000m
  - terrain:we_derivative_500m
  - terrain:we_derivative_2000m
  - terrain:sn_derivative_100000m
  target_var: "obs:wind_speed"