hydra:
  run:
    dir: ./
  output_subdir: ./

nwp_model: ch2  # Can only be ch2 for this project
d_map:
  ch2: 96

data_base_folder: ${oc.env:DATA_BASE_FOLDER}

model: 
  type: "RNN_Model_1"
  kwargs:
    num_layers: 4
    hidden_channels: 128
    kernel_size: 3
    dropout_p: 0.2
    causal_conv: False
    output_dist: LogNormal
    rnn_type: LSTM    

graph_kwargs:
  knn: 5
  threshold: 0.6

dataset:
  hours_leadtime: "${d_map.${nwp_model}}" # Depends on nwp model 
  train_split: 0.8
  val_split: 0.2
  test_start: '2024-05-16'
  train_val_end: '2023-09-30'
  features_pth: ${data_base_folder}/features.nc
  targets_pth: ${data_base_folder}/targets.nc
  predictors:
  - ${nwp_model}:wind_speed_ensavg
  - ${nwp_model}:wind_speed_ensstd
  - ${nwp_model}:mslp_difference_GVE_GUT_ensavg
  - ${nwp_model}:mslp_difference_BAS_LUG_ensavg
  - time:sin_hourofday
  - time:cos_hourofday
  - time:sin_dayofyear
  - time:cos_dayofyear
  - terrain:elevation_50m
  - terrain:distance_to_alpine_ridge
  - terrain:tpi_2000m
  - terrain:std_2000m
  - terrain:valley_norm_2000m
  - terrain:sn_derivative_500m
  - terrain:sn_derivative_2000m
  - terrain:we_derivative_500m
  - terrain:we_derivative_2000m
  - terrain:sn_derivative_100000m
  target_var: "obs:wind_speed"

training: 
  batch_size: 24
  loss: "MaskedCRPSLogNormal"
  gradient_clip_value: 1.0
  epochs: 8
  optim:
    algo: 'Adam'
    kwargs:
      betas: "(0.9, 0.999)"
      lr: 0.0001

    
  scheduler:
    algo: 'CosineAnnealingWarmRestarts'
    kwargs: 
      T_0: 10
      T_mult: 2
      eta_min: 0.000005

logging:
  mlflow_tracking_uri: ${oc.env:MLFLOW_TRACKING_URI, mlruns} # log locally 
  experiment_id: stgnn_wind_postproc
  
  